app/src/main/AndroidManifest.xml
app/src/main/java/com/ssu/bilda/MyInfoInputActivity.kt
app/src/main/java/com/ssu/bilda/PwInputActivity.kt
app/src/main/java/com/ssu/bilda/SignInActivity.kt
app/src/main/res/layout/activity_email_input.xml
app/src/main/res/layout/activity_my_info_input.xml
app/src/main/res/layout/activity_pw_input.xml
app/src/main/res/layout/activity_sign_in.xml
app/src/main/res/layout/activity_splash.xml
app/src/main/res/layout/spinner_major_set.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/spinner_major_items.xml
app/src/main/res/values/strings.xml

ex) ui/signup -> main
#5 회원가입(비밀번호)-로그인 화면 작업 완료
생략

[ui/#5] 회원가입(비밀번호)-로그인 화면 작업

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/com/ssu/bilda/BnvActivity.kt
app/src/main/res/drawable/bnv_selector_color.xml
app/src/main/res/drawable/ic_bnv_home.xml
app/src/main/res/drawable/ic_bnv_person.xml
app/src/main/res/drawable/ic_bnv_team.xml
app/src/main/res/drawable/shape_gray_line_rect.xml
app/src/main/res/layout/activity_bnv.xml
app/src/main/res/menu/menu_bnv.xml

ex) ui/bnv -> main
#10 바텀네비게이션 완성
바텀네비의 아이콘 클릭 시 첫 화면이 될 fragment는 추후 생성할 예정
생략

[ui/#10] bnv 완성

---

app/src/main/java/com/ssu/bilda/AddSubjectFragment.kt
app/src/main/res/drawable/bg_home_scroll.xml
app/src/main/res/layout/fragment_add_subject.xml
app/src/main/res/layout/item_rcv_home_add_subject.xml
app/src/main/res/values/colors.xml

ex) ui/home -> main
#13 프래그먼트로 구성하여 홈 화면위에 쌓는 형식으로 만들 예정
스크롤뷰 내에는 리싸이클러뷰 사용함
리싸이클러뷰 item 선택 시 색상 변경 => 코드로 구현(어댑터)
생략

[ui/#13] 홈 (과목 추가) 화면 완성

---

app/src/main/res/drawable/bg_dialog_btn.xml
app/src/main/res/drawable/bg_dialog_email.xml
app/src/main/res/layout/dialog_email.xml

ui/emaildialog -> main
#6 이메일 인증 관련 다이얼로그 작업 완료
생략

[ui/#6] 이메일인증 다이얼로그 작업 완료

---

app/src/main/java/com/ssu/bilda/BnvActivity.kt
app/src/main/java/com/ssu/bilda/SignInActivity.kt
app/src/main/res/layout/activity_bnv.xml
app/src/main/res/layout/activity_terms_of_privacy.xml
app/src/main/res/layout/activity_terms_of_use.xml

feat/bnv -> main
#34 바텀네비 기능 구현
생략

[feat/#34] 바텀네비 기능 구현

---

app/src/main/java/com/ssu/bilda/TermsActivity.kt
app/src/main/java/com/ssu/bilda/TermsOfPrivacyActivity.kt
app/src/main/java/com/ssu/bilda/TermsOfUseActivity.kt

feat/terms->main
#35 약관 화면 관련 기능 구현
https://github.com/SSU-OpenSource/Front-AOS/assets/102938120/846055d1-7a48-49e0-a2ec-e94903567431

[feat/#35] 약관 페이지 관련 기능 구현

---

app/src/main/java/com/ssu/bilda/BnvActivity.kt
app/src/main/java/com/ssu/bilda/ProjectStatusFragment.kt
app/src/main/java/com/ssu/bilda/SubjectAdapter.kt
app/src/main/res/layout/fragment_project_status.xml
app/src/main/res/layout/item_rcv_evalution_subject.xml

[feat] 평가 페이지 과목 리스트 리싸이클러뷰 구현

---

app/src/main/java/com/ssu/bilda/presentation/BnvActivity.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/MyInfoFragment.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/ProfileFragment.kt
app/src/main/res/layout/fragment_my_info.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_reset_password.xml

feat/mypage ->main
#44
생략 ( 추후 뷰 변경 후 테스트)

[feat/#44] 마이페이지 화면 전환 구현

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/ssu/bilda/presentation/mypage/ChangeNicknameActivity.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/ChangePasswordActivity.kt
app/src/main/res/drawable/ic_blue_next_btn.xml
app/src/main/res/layout/activity_change_nickname.xml
app/src/main/res/layout/activity_change_password.xml

[ui/#49] 마이페이지 뷰 변경 부분 디자인

---

app/src/main/java/com/ssu/bilda/presentation/mypage/ChangeNicknameActivity.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/ChangePasswordActivity.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/MyInfoFragment.kt
app/src/main/res/layout/activity_change_nickname.xml
app/src/main/res/layout/activity_change_password.xml
app/src/main/res/layout/fragment_my_info.xml
app/src/main/res/layout/fragment_profile.xml

feat/mypage -> main
#50 
Uploading 제목 없는 동영상 - Clipchamp로 제작 (1).mp4…

[feat/#50] 마이페이지 변경 부분 기능 구현

---

app/src/main/java/com/ssu/bilda/presentation/evaluate/TeammateEvalutionFragment.kt
app/src/main/res/layout/fragment_project_status.xml
app/src/main/res/layout/fragment_subject_status.xml
app/src/main/res/layout/fragment_teammate_evalution.xml
build.gradle.kts

feat/evaluation->main
#53 
Uploading 20231123_204834.mp4…

[feat/#53] 평가 페이지 뒤로가기 구현

---

app/src/main/res/layout/fragment_profile_refer.xml
app/src/main/res/layout/fragment_team_build_post_view_general.xml
app/src/main/res/layout/fragment_team_build_post_view_leader.xml
app/src/main/res/layout/item_rcv_teammate_profile.xml

[ui/#56] 팀 빌딩 페이지 디자인 변경

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/ssu/bilda/data/remote/App.kt
app/src/main/java/com/ssu/bilda/data/remote/TokenSharedPreferences.kt
app/src/main/java/com/ssu/bilda/data/service/EmailService.kt
app/src/main/java/com/ssu/bilda/presentation/BnvActivity.kt
app/src/main/java/com/ssu/bilda/presentation/sign/EmailInputActivity.kt
app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt
app/src/main/java/com/ssu/bilda/presentation/sign/PwInputActivity.kt
app/src/main/java/com/ssu/bilda/presentation/sign/SignInActivity.kt
app/src/main/res/layout/activity_bnv.xml
app/src/main/res/layout/activity_pw_input.xml

feat/signin -> main
#72 회원가입 api 붙이기 및 로그인 api + 세부 기능 구현
https://github.com/SSU-OpenSource/Front-AOS/assets/102938120/5f5cf8c9-24e1-4d4d-a0bd-55c49c2d67ec

[feat/#72] 회원가입 api 붙이기 및 로그인 api + 세부 기능 구현

---

app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt

[feat] SH에 유저 이름,닉네임,학번,학과 저장 내용 추가

---

app/src/main/java/com/ssu/bilda/presentation/sign/MyInfoInputActivity.kt
app/src/main/java/com/ssu/bilda/presentation/sign/SignInActivity.kt

[fix/#77] SH에 유저정보 저장안되는 문제 해결

---

app/src/main/java/com/ssu/bilda/data/common/ScoreItem.kt
app/src/main/java/com/ssu/bilda/data/remote/response/MyPageResponse.kt
app/src/main/java/com/ssu/bilda/data/service/MyPageService.kt
app/src/main/java/com/ssu/bilda/data/service/MypageService.kt
app/src/main/java/com/ssu/bilda/presentation/mypage/ProfileFragment.kt
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/item_rcv_profile_recieved_evaluation.xml

[feat/#84] 마이페이지 API 작업 및 세부 기능 구현

---

app/src/main/java/com/ssu/bilda/data/common/EvaluationTeam.kt
app/src/main/java/com/ssu/bilda/data/common/EvaluationTeamMember.kt
app/src/main/java/com/ssu/bilda/data/remote/response/EvaluationTeamResponse.kt
app/src/main/java/com/ssu/bilda/data/service/EvaluationService.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/SubjectAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateNameAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
app/src/main/res/layout/fragment_project_status.xml
app/src/main/res/layout/fragment_subject_status.xml
app/src/main/res/layout/item_rcv_evaluation_subject.xml

[feat/#86] 평가 페이지 API 작업 및 세부 기능 구현

---

app/src/main/java/com/ssu/bilda/presentation/adapter/UserSubjectAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_team_build_overview.xml
app/src/main/res/layout/fragment_team_details_by_subject.xml

- [x 기능 추가
ex) feat/login -> dev
#94

[feat] 과목추가, 유저가속한 과목, 과목 선택시 hasTeam에 따른 분기 완료

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/ssu/bilda/data/remote/request/GptCompletionChatRequest.kt
app/src/main/java/com/ssu/bilda/data/remote/response/GptCompletionChatResponse.kt
app/src/main/java/com/ssu/bilda/data/service/ChatService.kt
app/src/main/java/com/ssu/bilda/presentation/home/ChatBotActivity.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/res/drawable/bg_chat.xml
app/src/main/res/layout/activity_chat_bot.xml

[feat] 챗봇 붙임

---

app/src/main/java/com/ssu/bilda/data/common/TeamsOfSubjectDTO.kt
app/src/main/java/com/ssu/bilda/data/remote/response/ResponseDtoListTeamsOfSubjectTDTO.kt
app/src/main/java/com/ssu/bilda/data/remote/response/TeamResponse.kt
app/src/main/java/com/ssu/bilda/data/service/TeamService.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/TeamsAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/home/AddSubjectFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
app/src/main/res/layout/fragment_team_build_overview.xml

[feat] 모집중 부분

---

app/src/main/java/com/ssu/bilda/data/remote/response/ResponseDtoListTeamsOfSubjectTDTO.kt
app/src/main/java/com/ssu/bilda/data/remote/response/TeamResponseDTO.kt
app/src/main/java/com/ssu/bilda/data/remote/response/UserResponseDTO.kt
app/src/main/java/com/ssu/bilda/data/service/TeamService.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/TeamMembersAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/res/layout/fragment_add_subject.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_team_build_overview.xml
app/src/main/res/layout/fragment_team_details_by_subject.xml

[feat] 리싸이클러뷰 중간단계

---

app/src/main/java/com/ssu/bilda/data/common/TeamDetail.kt
app/src/main/java/com/ssu/bilda/data/common/TeamInfo.kt
app/src/main/java/com/ssu/bilda/data/common/TeamMember.kt
app/src/main/java/com/ssu/bilda/data/common/TeamMemberWithNickName.kt
app/src/main/java/com/ssu/bilda/data/common/UserData.kt
app/src/main/java/com/ssu/bilda/data/remote/request/CreateTeamRequest.kt
app/src/main/java/com/ssu/bilda/data/remote/request/TeamJoinRequest.kt
app/src/main/java/com/ssu/bilda/data/remote/response/JoinRequestResponse.kt
app/src/main/java/com/ssu/bilda/data/remote/response/MyPageReferResponse.kt
app/src/main/java/com/ssu/bilda/data/remote/response/RejectJoinRequestResponse.kt
app/src/main/java/com/ssu/bilda/data/remote/response/TeamInfoResponse.kt
app/src/main/java/com/ssu/bilda/data/remote/response/TeamJoinResponse.kt
app/src/main/java/com/ssu/bilda/data/service/TeamAcceptRequestService.kt
app/src/main/java/com/ssu/bilda/data/service/TeamJoinRequestService.kt
app/src/main/java/com/ssu/bilda/data/service/TeamRejectRequestService.kt
app/src/main/java/com/ssu/bilda/data/service/TeamService.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/TeammateProfileAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/evaluate/ProjectStatusFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/AcceptJoinRequestFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/ProfileReferFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewGeneral.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildWritingFragment.kt
app/src/main/res/drawable/item_request_gray_box.xml
app/src/main/res/layout/fragment_accept_join_request.xml
app/src/main/res/layout/fragment_team_build_post_view_general.xml
app/src/main/res/layout/fragment_team_build_post_view_leader.xml
app/src/main/res/layout/item_rcv_request.xml
app/src/main/res/layout/item_rcv_teammate_profile.xml

[feat] 글 조회~ 프로필 조회 (요청 보내기, 수락, 거절) 구현

---

app/src/main/java/com/ssu/bilda/presentation/adapter/UserSubjectAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_project_status.xml
app/src/main/res/layout/item_rcv_home.xml
app/src/main/res/layout/item_rcv_teambuild_name.xml

[feat] 홈 화면 과목 리싸이클러뷰 구현

---

app/src/main/java/com/ssu/bilda/data/common/UserData.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
app/src/main/res/layout/fragment_my_info.xml

feat/teambuilding -> main
요청 리스트 닉네임으로 변경
회원 탈퇴 삭제 뷰 수정
임시 버튼이 없어서 nickname 테스트 못함 추후 확인 필요

[fix] 오류 수정

---

app/src/main/java/com/ssu/bilda/presentation/adapter/HomeTeamMemberAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/res/layout/fragment_team_build_overview.xml
app/src/main/res/layout/fragment_team_details_by_subject.xml
app/src/main/res/layout/item_rcv_home_team_members.xml

-[X] 버그 수정
feat/tembuilding -> main

[fix] 홈 팀원 리싸이클러뷰

---

app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt

feat/evaluate
평가항목 hasevalutated 에 따른 분기

[feat] 평가항목 hasevaluated 에 따른 분기처리

---

app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt

[fix] 홈화면 분기처리 수정

---

app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
app/src/main/res/layout/activity_sign_in.xml

[feat] 팀플종료api 및 서브젝트코드관련

---

app/src/main/java/com/ssu/bilda/data/remote/UserSharedPreferences.kt
app/src/main/java/com/ssu/bilda/presentation/evaluate/SubjectStatusFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildWritingFragment.kt

feat/teambuidling -> main
팀 생성 subjectId 받아오기 구현

[feat]  팀 생성 subjectId 받아오기 구현

---

app/src/main/java/com/ssu/bilda/data/remote/response/ResponseDtoListTeamsOfSubjectTDTO.kt
app/src/main/java/com/ssu/bilda/presentation/adapter/TeamsAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildOverviewFragment.kt
app/src/main/res/layout/item_rcv_teambuild_name.xml

[feat] 모집중 관련 리싸이클러뷰 수정 및 분기처리

---

app/src/main/java/com/ssu/bilda/presentation/home/HomeFragment.kt
app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt
app/src/main/res/layout/fragment_home.xml
app/src/main/res/layout/fragment_team_details_by_subject.xml

[feat] 과목이름 넘기기 및 화면 전환 기타 등등 ,, 

---

app/src/main/java/com/ssu/bilda/presentation/home/TeamDetailsBySubjectFragment.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt

ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

[fix] 요청 확인 페이지 연결 성공

---

app/src/main/java/com/ssu/bilda/presentation/adapter/RequestAdapter.kt
app/src/main/java/com/ssu/bilda/presentation/teambuild/TeamBuildPostViewLeader.kt

[fix] 요청 받기 페이지 오류 수정
